# Application Configuration
server:
  port: 8091
  # Needed for spring-boot-starter-validation to show messages
  error:
    include-message: always
    include-binding-errors: always

# To see H2 Console in a web browser
# Open: http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # DB Definition
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

# EUREKA SERVER CONFIG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

# ========================
# ACTUATOR
# ========================
management:
  endpoints:
    web:
      exposure:
        include: "*"